### ISSUE TITLE
Possible way to implement Information bar in top left corner or at least more centrally so its not stretched?

### ISSUE THREAD

**Issue by Draxirch** [vitor251093/KHMelonMix#142]
As the title suggests. 
Either we can try to position it in the left corner or we can try centralising it so it's not stretched?

**Comment by vitor251093** [comment]
Implementation will be done for MM 0.4.0.

The Information header will only be visible during two circumstances: when it appears for the first time, and while the third HUD Toggle state is being shown.

Basically would turn the third state in the "regular KH state during missions", while the first one is "regular KH state while exploring", and the second one are Days exclusive HUD elements (which are basically mission details).

**Comment by vitor251093** [comment]
Finished

![2024-07-08_16-38](https://github.com/vitor251093/KHMelonMix/assets/8976483/8e31087e-3b77-48bf-9819-be999de87a59)
