### ISSUE TITLE
Mission gauge not appearing in pause menu

### ISSUE THREAD

**Issue by Ssheph95** [vitor251093/KHMelonMix#148]
After installing version 0.3.0 for Windows, the mission gauge no longer appears in the pause menu. 
Shown below is from mission 57 on 0.3.0

![No Gauge](https://github.com/vitor251093/KHDays_FM/assets/97009666/d34b483d-a5f1-431a-a535-8a9383457751)

This is from the same savestate point in 0.2.2

![Gauge](https://github.com/vitor251093/KHDays_FM/assets/97009666/06525e8a-4c72-48d3-be7f-d352c627dc56)

All config settings within MelonDS are the same, the only change between the two was the MelonDays Executable.

**Comment by TheKiwiKat** [comment]
I've been building very frequently in between commits, and I've found this bug appeared directly after building with this commit: https://github.com/vitor251093/KHDays_FM/commit/534f841f8bfca5e8f60e24f2ca32228490d5169a

Mission Gauge appears as it should before this change.

**Comment by vitor251093** [comment]
Interesting. That commit had the intention to avoid showing a cropped 3D scene during double 3D scenes, but maybe the mimimap detection isn't working as expected because during pause things get slightly darker.

**Comment by vitor251093** [comment]
I've reverted the change so the mission gauge will be back to the pause menu. It will cause a bug on double 3D scenes for now though, but that's minor in comparison. I will keep this ticket open to fix that second bug

**Comment by vitor251093** [comment]
Fixed for good now
