### ISSUE TITLE
Hearts gauge display resize causes visual glitches 

### ISSUE THREAD

**Issue by Ssheph95** [vitor251093/KHMelonMix#158]
**Describe the bug**
The resizing of the hearts gauge causes rare visual issues when other HUD elements are near that area of the screen.

**To Reproduce**
This is most observable when the targeting cursor is on an enemy in the top left corner, or when the hearts gauge itself reaches the thousands digit.

**Expected behavior**
ideal behavior is that the hearts gauge resize shouldn't impact other HUD elements. Or it may be that the hearts gauge needs to be un-resized if its bounding box is interfering with the HUD overall.

**Screenshots**
![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/cc761916-72aa-4c0a-b450-3bb90e2e475b)
![image](https://github.com/vitor251093/KHDays_FM/assets/97009666/7158e9a7-eac5-4aa4-8629-b2fbb2558914)

**Desktop (please complete the following information):**
 - OS: Windows
 - Melon Mix Version: Action build 316 for Windows
 
**Additional context**
Mentioned this on the discord last week but forgot to actually create the issue for it. This issue may be related to issue #156 in that it has to do with the uppermost HUD elements in the play window,

**Comment by vitor251093** [comment]
> This issue may be related to issue #156 in that it has to do with the uppermost HUD elements in the play window,

Those are actually different. The heart is rendered using the DS 3D renderer, while the enemy name is rendered using the DS 2D renderer, so the approach to change their size and aspect ratio is different.

Still, this is indeed a bug that needs to be dealt with.

**Comment by vitor251093** [comment]
Based on my tests, this seems to be now fixed in the latest Actions build. @Ssheph95 could you please confirm?

**Comment by Ssheph95** [comment]
I've run about half a dozen missions and have been unable to reproduce the lock-on stretching behavior or the 4th digit heart counter stretching, I think we can consider this one officially solved!
