### ISSUE TITLE
Remove ROM restriction 

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHMelonMix#165]
It has been requested that the ROM restriction could be removed, in order to allow other games to be played with the Melon Mix touch screen controls.

**Comment by CpazR** [comment]
I'm curious how this would work. Aren't there a ton of harcoded changes specifically for the restricted roms?

Wouldn't it make mkre sense to have a separate fork with the desired control changes exclusively?

Maybe I'm just not fully understanding the ask.

**Comment by vitor251093** [comment]
That used to be the case. But ever since I added initial ReCoded support, the hard coded changes are separated per game code, except for the touch screen controls.

So basically, it would be simple to create a fallback state, where everything works just like normal melonDS, but with touchscreen controls.
