### ISSUE TITLE
Steam Deck settings

### ISSUE THREAD

**Issue by Chalking** [vitor251093/KHMelonMix#170]
I changed some settings on steam deck and now the app immediately closes upon opening it. I have no idea where the config file is to change it back, so I can't change it or delete it. Since the download is just the app image, redownloading it just inherets the same broken settings. 
Please make where the config file is clear in the install tutorial for steam deck, thank you.

**Comment by vitor251093** [comment]
I don't which config could make the Melon Mix not even launch, but you can find the config file at ~/.config/khDaysMM/melonDS.ini
