### ISSUE TITLE
Yellowish filter appears when there is a big box with choices

### ISSUE THREAD

**Issue by 2Bish** [vitor251093/KHMelonMix#171]
**Describe the bug**
A yellowish filter appears on the outer parts of the screen when you have to answer some questions.

**To Reproduce**
1. Go to mission 23 "Search for Xion" (Also work on mission 27)
2. Do the mission until you need to do Pence's Quizz
3. See error when you have to answer him

**Expected behavior**
The coulor on the screen should be normal.

**Screenshots**
![20240625095548_1](https://github.com/vitor251093/KHMelonMix/assets/174067111/98bd41ff-9729-4928-bae1-3a620b80f14b)
![20240624040449_1](https://github.com/vitor251093/KHMelonMix/assets/174067111/ae46e97f-1b0d-40c0-9c17-6531b5237084)

**Desktop (please complete the following information):**
 - OS: Steam OS 3.5.19
 - Melon Mix Version 0.3.1

**Additional context**
 The save state attached is just before you need to talk to Pence, to allow to see what happens before in the case it is needed. It is also in .zip because GitHub didn't allow the raw file.
[game.zip](https://github.com/user-attachments/files/16022100/game.zip)

**Comment by vitor251093** [comment]
Fixed in the latest Actions build

![2024-06-28_22-47](https://github.com/vitor251093/KHMelonMix/assets/8976483/6645bbbc-4406-48cc-a4b0-fce5845e4659)
