### ISSUE TITLE
Random Visual Bugs

### ISSUE THREAD

**Issue by ZLGNF** [vitor251093/KHMelonMix#173]
Ok so first one we got is the timer in Mission Mode: 
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/a1e68101-76ff-42ee-97aa-97834dec6a74)

Second, we have the timer in the minigame covering the Chain text
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/5ed21b78-c259-425c-b2a3-5f8d4cf4262c)

Third, we have Sora's ghost coming back for 1 frame, I'm assuming this is the case for every Sora gameplay mission.

https://github.com/vitor251093/KHMelonMix/assets/103905827/7cfb329e-b94a-485b-a6c4-32d7b6647dab

4th... hum tbh I don't really know what's happening with this one
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/b80276a9-cfae-485b-acc6-b7e087c60585)

5th, we have the dialog boxes with the choices that still show these artifacts before and after they show up
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/6a387446-57fe-4629-8642-93b85fd41f65)

6th we still have the top screen showing in the mission results screen for 1 frame

https://github.com/vitor251093/KHMelonMix/assets/103905827/c7feb0f7-9fdf-4cfe-b67b-d2a61cee18c8

You're gonna have to slow down to actually see that happening but it's there. You can also see the 5th issue in action as well there.

**Comment by sandwichwater** [comment]
i know for atleast the second issue its because the heart counter and chain text were lowered to make room for the information bar therefore causing the overlap , but since that doesnt need to be visible at all times anymore with the recent changes that added it to the pause menu and 3rd toggle state itll probably be fixed simply by moving it back up

**Comment by vitor251093** [comment]
1. Fixed
2. Fixed
3. Not fixed yet
4. Fixed
5. Not fixed yet
6. Considering how fast it is, trying to fix it will probably cause more bugs, so I will leave it that way for now
