### ISSUE TITLE
KH Re:Coded Visual Bug

### ISSUE THREAD

**Issue by ivolivari213** [vitor251093/KHMelonMix#175]
Hello, on KH Recoded the Command Matrix is black:

![image](https://github.com/vitor251093/KHMelonMix/assets/96542650/4252bbe0-c5fc-4ddd-bb23-54113421e0e0)

**Comment by vitor251093** [comment]
Bugs involving Re:Coded are currently not being accepted, since Re:Coded support is still on initial stages, so a lot of things are broken right now.
