### ISSUE TITLE
Mouse/touch support in panel menu

### ISSUE THREAD

**Issue by TheConfuZzledDude** [vitor251093/KHMelonMix#177]
Making changes to the panel setup with only the controller can be quite annoying, but the current configuration means that using the touchscreen to drag and drop panels is very difficult.

Currently, the bottom screen content is added to the top screen, and then only the top screen is shown, so obviously trying to click won't work. Switching the screen layout to show the bottom screen then means that the bottom screen is shown twice, and also the scaling of the panel icons is incorrect, so you can't really tell what you're doing.

Could a touch mapping be added to the top screen for the panel menu? Or maybe easier would be disabling the special single screen combo and switching to show both screens in a horizontal view when the panel menu is entered

**Comment by sandwichwater** [comment]
should probably be grouped together with #84 and just have a setting to unlock the mouse in general

**Comment by vitor251093** [comment]
Implemented on the latest Actions build
