### ISSUE TITLE
Information Header bugs

### ISSUE THREAD

**Issue by ZLGNF** [vitor251093/KHMelonMix#180]
Not sure I would call all of these bugs but for the sake of simplicity here's what we got:

1. The information header should be hiding the heart counter, at least, that's how it was in the original
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/a7e668df-c494-434d-8db6-e4191c43d794)
2. Currently, if you pause the game in the moments where the game displays the information in the top screen, the information in the pause screen will show the bottom. ![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/cea80820-2399-45db-826d-18f63366830b)
3. Another thing is how the new updated look for the header is not showing in the pause version, at least not fully. ![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/ff378ace-f5fe-415f-a9ae-97b290d8b774)
4. So, when paused, the information tab will freeze like everything else. The problem here is that there's missions (usually in the Challenge mode) where the information is 2 different texts and the game will be scrolling through that text so you can eventually read both. But since the pause will freeze everything, you'll end up with stuff like this: 
![image](https://github.com/vitor251093/KHMelonMix/assets/103905827/fc916087-645e-4461-aa32-a898f08e2e38)
Ideally, you would have to make it so the text never stops scrolling even when the game is paused but I don't know how feasible that is.

**Comment by vitor251093** [comment]
Items 2 and 3 fixed

**Comment by vitor251093** [comment]
Item 1 fixed

**Comment by vitor251093** [comment]
Item 4 will be dealt with on #183
