### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by Arachnosuchus** [vitor251093/KHMelonMix#185]
Is there a way to trick the game into thinking I'm playing with another person to get the crowns?
I tried running two instances in parallel but they don't find each other.

**Comment by sandwichwater** [comment]
which version are you playing ¿ every version except for the jp version has the ability to earn crowns in singleplayer mission mode

**Comment by Arachnosuchus** [comment]
> which version are you playing ¿ every version except for the jp version has the ability to earn crowns in singleplayer mission mode

I'm playing the Japanese version.

**Comment by vitor251093** [comment]
Are you launching the second instance from within the Melon Mix itself?
