### ISSUE TITLE
Game scene bugs

### ISSUE THREAD

**Issue by ZLGNF** [vitor251093/KHMelonMix#187]
1.  Bottom Screen showing in this Cave of Wonders scene

![image](https://github.com/user-attachments/assets/aecab1d0-9da1-4a5e-8dd9-955232cf881b)

2. Save Screen is inconsistent 

https://github.com/user-attachments/assets/ad655ae0-1b0b-41ae-bdb3-ae49e7f59aa6

3. Pause menu flickering, not sure what is causing this and how it sometimes happens and other times it doesn't

https://github.com/user-attachments/assets/e3f9fd5f-4539-4462-b8c6-2fc3a07c995b

4. Mission Report flickering, I've already reported it but I'll mention again since it was in an issue that was closed

https://github.com/user-attachments/assets/ec82aad0-4345-4a1f-a546-4faa844b5ac9

5. Dialogue box briefly fills the entire screen when unpaused, this one is weird cuz it not all scenes do this

https://github.com/user-attachments/assets/bb42c83b-f04a-4836-a847-0856bb745fd2

**Comment by leftshoe18** [comment]
That Cave of Wonders bug also appears in the cutscene where Xemnas introduces Kingdom Hearts to the boys.

**Comment by vitor251093** [comment]
Fixed issues 1, 2, 3 and 4 with the last Actions builds. Bug 5 is still ongoing.

**Comment by vitor251093** [comment]
I will create a new issue for single frame issues, so they can be dealt with in the future

**Comment by vitor251093** [comment]
New issue created for problem 5, #228
