### ISSUE TITLE
Double 3D Scenes Bugs

### ISSUE THREAD

**Issue by ZLGNF** [vitor251093/KHMelonMix#189]
1. So, a couple of Sora scenes in the dialogue scenes don't show up properly and some not at all. It's gonna be important to start keeping track of these scenes to see how they look
![image](https://github.com/user-attachments/assets/58bb8374-b51f-4002-9f03-7c50bde7b146)
![image](https://github.com/user-attachments/assets/601b2bcc-debf-404b-a67b-b59403d4502d)
2. Sora scene transitions are too long, especially noticeable in missions like Day 152 Mission 47 or Day 224 Mission 61 when you have 2 or 3 scenes in a row, you can't see Roxas until the final scene is done, which can lead to death (specially the Olympus one)

https://github.com/user-attachments/assets/0c632525-1975-48a2-ac2a-d3ac907b6920

3. Pausing during Sora moment shows Roxas

https://github.com/user-attachments/assets/ed03a572-95bf-403d-af6b-ad5fb0c1bfa8

**Comment by vitor251093** [comment]
Item 3 will be solved by #244

**Comment by vitor251093** [comment]
Item 1 was solved on the latest Actions builds

**Comment by vitor251093** [comment]
Item 2 shows two problems:
- No HUD for Sora
- Long static periods

Problem 2.2 was solved on the latest Actions builds. Problem 2.1 wiil be solved by #150
