### ISSUE TITLE
Emulation pause during HD cutscene

### ISSUE THREAD

**Issue by EpicGamerNaeNae** [vitor251093/KHMelonMix#190]
If the emulation is paused during HD cutscene playback, occasionally nothing will happen. If the pause is left on, once gameplay resumes, turning it off will freeze the game until the emulation is reset, or sometimes it will simply not pause not matter how many times pause is pressed.

1. Watch an HD cutscene during gameplay
2. Click System>Pause (this makes a checkmark appear next to the pause option)
3. If the cutscene doesn't pause, wait for the cutscene to end
4. Click System>Pause again (the checkmark disappears)
5. The game freezes or it doesn't pause

Expected behavior:
Using the emulator pause feature should always pause the game when on and resume when off.

 - OS: Windows 11
 - Melon Mix Cutscene replacement actions build from the July 18th 2024 (https://github.com/vitor251093/KHMelonMix/actions/runs/10001756997)

**Comment by EpicGamerNaeNae** [comment]
In the latest builds, while in the theater, instead of doing nothing when pressed during an HD cutscene, the pause button will mute the game volume (this can be seen in the theater where some cutscenes occasionally play both the HD and the original audio), which persists until the pause is turned off, at which point the pause functionality returns to normal

**Comment by vitor251093** [comment]
It's now possible (on the latest Actions build) to pause the HD cutscenes using the emulator pause functionality
