### ISSUE TITLE
When the Information Bar is visible, a small box will appear during dialogue.

### ISSUE THREAD

**Issue by ColossusSteppes** [vitor251093/KHMelonMix#202]
When the HUD is set to show the information bar, speaking to an NPC will show a grey rectangle in the top-middle of the screen (where the information bar would usually fade out). It's only a minor issue, but I thought I'd mention it.

Windows 11
[Action Version](https://github.com/vitor251093/KHMelonMix/actions/runs/10155902423)

![image](https://github.com/user-attachments/assets/0882d634-9137-4663-a390-087a9752813d)

**Comment by vitor251093** [comment]
Can you confirm if this bug was fixed by the last commit?

**Comment by ColossusSteppes** [comment]
Fixed on the Windows version, though when testing the Steam Deck version it would no longer open.
Launching through the .sh file gave this message.

![Screenshot_20240801_055540](https://github.com/user-attachments/assets/0e03adfe-c09d-4dd8-a0d5-a710c91dae9f)

If you'd rather this be placed in a separate issue let me know. But as mentioned, it now works properly on Windows, so thank you!

**Comment by vitor251093** [comment]
That's really weird. I will close this issue, but could you open the .sh file with a text editor and past the contents of it here? That doesn't seem right
