### ISSUE TITLE
netplay in the possible future?

### ISSUE THREAD

**Issue by zakilj3** [vitor251093/KHMelonMix#219]
hello, so as of right now, melonds's "nightly" build(which are on their action tab) implemented LAN multiplayer (for example between two pc on a same local network) for now this feature is quite experimental and from my personal test doesn't work sadly online(tried with some vpn)however they plan as well to work on a proper netplay feature.

my question is simple,once netplay get properly implemented and is also working for this game on melonDS, will the project be updated to support netplay as well?(they consider adding netplay as part of their "season 4")

**Comment by vitor251093** [comment]
Yes
