### ISSUE TITLE
Some HD Cutscenes Loop Infinitely

### ISSUE THREAD

**Issue by RedDragoon101** [vitor251093/KHMelonMix#221]
The "Good Tidings Friends"

1. Watch Cutscene
2. Watch Cutscene again
3. Watch Cutscene for a third time
4. Get confused on why the game hasn't moved on
5. Good Tidings Friends
6. Profit?!?

Cutscene should only play once lol

![image_2024-08-12_201108340](https://github.com/user-attachments/assets/0550fd20-242c-480a-91ae-ef15d298757e)

 - OS: Windows 10
 - Melon Mix Version 0.4.1

**Comment by nuttyaaaaa** [comment]
that happened to me as well

**Comment by vitor251093** [comment]
I've made a change that should fix this. I just need to perform my tests.

- **Single cutscene:** N/A
- **Sequential cutscene:** N/A
- **Credits:** N/A
- **The two cutscenes before Day 7:** N/A
- **Intro on waiting on title screen:** N/A
- **Theater:** Tested waiting and skipping

I will update this comment as I test

**Comment by vitor251093** [comment]
Fixed on the last Actions build
