### ISSUE TITLE
360 degree movement.

### ISSUE THREAD

**Issue by DrBolt97x** [vitor251093/KHMelonMix#231]
Issue: There are only 8 directions to move in due to original button control.

Possible Solution: I have a version of DeSmuMe, similar to Melon Mix, but designed for Mario 64 DS. Among other features, it adds 360 degree movement with the left analogue stick. I think its hard to find online but I have a copy if you would like me to send it over for you to analyse. If you are interested in 360 degree movement, it would improve the game dramatically. 

Let me know if you want me to send it over to you.
Thanks

**Comment by vitor251093** [comment]
I mean, currently we already have an issue for that (#40), but the Desmume may be useful if you have its source code

**Comment by DrBolt97x** [comment]
How would I find that? I'm not a programmer or coder. I am good at figuring things out tho.

**Comment by vitor251093** [comment]
If you don't know where to find, then most likely you don't have it xD

The source code is, essentially, the input used to create an executable. If you only have the source code, you can produce the executable. If you only have the executable, you can't get the original source code back.

There are decompilation techniques (which means getting source code from executable), but they won't give you a human readable code. I mean, it's possible to analyze it, but that would take more time than analysis Kingdom Hearts 358/2 Days directly.

**Comment by IcyWind14** [comment]
[Here's the link](https://github.com/LRFLEW/AM64DS_DeSmuMEl) to the github for the SM64 Analog Desmume.

**Comment by DrBolt97x** [comment]
i was literally just messaging you to say i found it

**Comment by DrBolt97x** [comment]
https://github.com/LRFLEW/AM64DS_DeSmuME/releases/tag/v1.1-3ba3821

**Comment by DrBolt97x** [comment]
Your link doesn't seem to be working? Might just be my laptop but here's a link to the github page with the source code

https://github.com/LRFLEW/AM64DS_DeSmuME/releases/tag/v1.1-3ba3821

**Comment by IcyWind14** [comment]
Yeah, an l somehow got added to the url when I copy-pasted the link, fixed it now.

**Comment by DrBolt97x** [comment]
Hopefully its helpful

**Comment by ZLGNF** [comment]
This isn't gonna be a simple copy and paste solution, the big difference between Mario and Days is that Mario 64 DS already HAS the 360º movement in the game, that Desmume project is using what's already inside that game. Days doesn't have that.

**Comment by vitor251093** [comment]
This issue will be handled in #40
