### ISSUE TITLE
Weird screen shifting and black screen in mission mode

### ISSUE THREAD

**Issue by NezcalSpindrake** [vitor251093/KHMelonMix#232]
During a mission mode tutorial, after hitting start on a tutorial popup, screen splits and half-black during the fadeout back to gameplay

Start a mission mode holo-mission with a tutorial.
Trigger tutorial.
Clear tutorial with start button.

**Expected behavior**
Display should stay as a single screen like tutorials do in main gameplay modes.

**Screenshots**
https://youtu.be/S7sNKozBK0c

**Desktop (please complete the following information):**
Windows 10
MM 0.4.1

**Comment by vitor251093** [comment]
Fixed on the latest Actions build
