### ISSUE TITLE
Black Box appears over Death Screen

### ISSUE THREAD

**Issue by RedDragoon101** [vitor251093/KHMelonMix#234]
Possible that it is the Mission Progress Bar staying on screen

1. Open Save
2. Select the Shadow Globs Mission
3. Die

The Black Box shouldn't be there

![image_2024-08-18_112405645](https://github.com/user-attachments/assets/a5c50c65-b637-461e-8c44-662057760bcd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Melon Mix Version: Latest Dev Build

**Comment by vitor251093** [comment]
[Black Box Die.zip](https://github.com/user-attachments/files/16650204/Black.Box.Die.zip)

**Comment by vitor251093** [comment]
Fixed on the last Actions build
