### ISSUE TITLE
New floating dialog box should be togglable, or be bigger

### ISSUE THREAD

**Issue by khHER0** [vitor251093/KHMelonMix#237]
Since not everyone might be playing Melon Mix on a big screen at home (For example they could be playing on laptops, Steam Deck, other similar screen sized devices etc.) ...The mini-sized dialog boxes introduced in Melon Mix 0.3 & later it seems have an even smaller tiny font size that looks less easy to read than the original.

Is it possible to add an emulator config menu option to switch to the default dialog boxes of original 358 Days for anyone who still wants those box/font sizes?

Here is a screenshots comparison of Kingdom Hearts dialog box/font sizes from various Kingdom Hearts games. Original 358Days is in the center middle, with Melon Mix's miniaturized dialog box/font sizes at both center top & center bottom for comparison. (The MM miniaturized dialogs seem to look like the smallest tiny fonts least easy to read compared to other Kingdom Hearts games I could find, at least to me??)
![khTextFontSizeComparisons](https://github.com/user-attachments/assets/cde33abb-5071-46fb-bbbd-96de527c30a2)

**Comment by DrBolt97x** [comment]
I agree. I play on my tv but I have bad eyes so it puts a lot of strain on them

**Comment by vitor251093** [comment]
I didn't realize they looked so small, but when looking at the image there's no doubt.

The floating boxes are smaller when compared with the original dialogs. Another option may be keeping the original height. The text should look as visible as the Re Chain of Memories one after doing that.

There's an internal variable (currently not exposed) called HUD Size. I may attach the HUD Size to the dialog as well, so people can control how big or small it should be.

**Comment by vitor251093** [comment]
![2024-09-04_21-27](https://github.com/user-attachments/assets/9037604f-ae70-4368-964c-ec0556d11001)

Dialog box increased in the latest Actions build
