### ISSUE TITLE
Mission 90 breaks the whole point

### ISSUE THREAD

**Issue by RedDragoon101** [vitor251093/KHMelonMix#238]
During the cutscene before placing the Device in Agrabah, the Whole of Melon Mix just... breaks

1. Go to Mission 90
2. Cry

It def shouldn't look like this lol

![image_2024-08-22_191115735](https://github.com/user-attachments/assets/95fe722e-d43b-468a-ade2-4d6f7c96dc49)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Melon Mix Version: Newest Dev Build

**Comment by vitor251093** [comment]
Fixed in latest Actions build
