### ISSUE TITLE
Recoded pause menu only shows a sliver

### ISSUE THREAD

**Issue by 3RR0R-C0D3-4O4** [vitor251093/KHMelonMix#240]
**Describe the bug**

opened the pause menu to skip a cutscene and the pause menu only showed a portion

**To Reproduce**
1. Go to '...'  a cutscene
3. Click on '....' the pause button (or start)
4. Scroll down to '....' irrelevant
5. See error

**Expected behavior**
A clear and concise description of what you expected to happen. was hoping for the pause menu to pop up. duh

**Screenshots**
If applicable, add screenshots to help explain your problem. wait i can do that? just a sec
![Screenshot (3)](https://github.com/user-attachments/assets/8314f2c6-3030-4399-9bdf-0f1ba361dd0f)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Melon Mix Version [e.g. 22] it says 0.4.1

**Additional context**

**Comment by vitor251093** [comment]
Bug reports for ReCoded currently aren't being accepted, until it leaves the WIP state
