### ISSUE TITLE
HD Cutscene "hd848.mp4" is missing music

### ISSUE THREAD

**Issue by IcyGoal** [vitor251093/KHMelonMix#242]
**Describe the bug**
The HD cutscene mentioned in the title has no music.

**To Reproduce**
N/A. Issue is not with Melon Mix itself, but with the mp4 file for the cutscene.

**Expected behavior**
Cutscene should have music. [For reference](https://youtu.be/mY6kflxFbek?si=aE3AlQ43kGGZZ4C4&t=9323) (DO NOT CLICK IF YOU HAVE NOT BEATEN THE GAME! MAJOR SPOILERS!)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Melon Mix Version 0.4.1

**Additional context**

**Comment by sandwichwater** [comment]
this is known and is due to the lack of music replacement . the original games plays the music in engine across those two scenes , as a result they are silent with replacement until we can find a way to play music at specific times

**Comment by vitor251093** [comment]
This issue will be handled by #204
