### ISSUE TITLE
Non-standard characters in filepath prevent .toml creation

### ISSUE THREAD

**Issue by TheGershon** [vitor251093/KHMelonMix#246]
On Windows, versions above 3.2 can't create a .toml file if they're within a path that contains non-standard characters (for instance, ∕ instead of / in order to have a forward slash in the folder title). Renaming the folder to let it create one and then renaming it back makes the .exe unable to launch.

Copying a .ini from a version ≤3.2 (or vanilla MelonDS) without a .toml present lets it load settings, but changes don't get saved.

**Comment by vitor251093** [comment]
Does the same bug also happens with melonDS's latest Actions build (not the last official release, the last build from the GitHub Actions tab).

**Comment by TheGershon** [comment]
Nope, melonDS-emu/melonDS/actions/runs/10745062014 creates a .toml with no issue

**Comment by vitor251093** [comment]
Checking src/frontend/qt_sdl/Config.cpp changes in the melonDS repo, it seems like they fixed that 2 months ago.

So this should be fixed once we merge the latest melonDS version on the Melon Mix.

**Comment by vitor251093** [comment]
This bug should now be fixed. We just need to validate

**Comment by TheGershon** [comment]
Unfortunately, it is not. Just checked with 0.4.5

**Comment by vitor251093** [comment]
The fix is on the latest Actions build

**Comment by TheGershon** [comment]
Oops, my mistake. Just checked with actions/runs/11510329790 and the issue is indeed fixed!

**Comment by TheGershon** [comment]
Two years later, this problems strikes again. A bit differently this time though, as the .toml gets created, but MelonMix refuses to open once one exists.
I haven't played in quite a while, so I'm not sure if this is a recent issue. For the record, melonDS standalone (from GitHub actions, so maybe not Stable) doesn't have this issue and works normally with a ∕ in the filepath.
