### ISSUE TITLE
Compute Shader causes horrific texture warping.

### ISSUE THREAD

**Issue by ValiantBlade** [vitor251093/KHMelonMix#248]
Exactly as the issue describes, I'm using the scene dump for Days, US ROM, XenoPhobia dump specifically, everything works fine in OpenGL regular, but compute shaders causes horrific texture warps. This screenshot speaks for itself.

![GitHub - vitor251093_KHMelonMix_ Kingdom Hearts 358_2 Days - Melon Mix (DS Emulator) — Mozilla Firefox 17-Sep-24 06_49_55](https://github.com/user-attachments/assets/e0283dcf-055d-4eaa-b414-2f2f897a8f9a)

My version is 0.4.4

Being this is a shader issue, I'm going to provide driver version and card info.

Nvidia 3070 Ti, Driver Version 561.09
Windows 11, Version 10.0.26100, Build 26100.

**Comment by sandwichwater** [comment]
this is a texture cache overflow coming from the melonds side of things , theyd have to fix it on their end . as of right now theres no benefit to playing on the compute shader so stick to classic opengl as its much more stable

**Comment by ValiantBlade** [comment]
Got it, feel free to close this since this is an upstream issue.

**Comment by vitor251093** [comment]
Since we already have another issue to keep track of the melonDS bug (#105), I will close this one
