### ISSUE TITLE
CRC error unpacking hd826.mp4 from assets (HD cutscenes)

### ISSUE THREAD

**Issue by hyouriku** [vitor251093/KHMelonMix#249]
**Describe the bug**
Unpacking the Cutscenes zip (downloaded on 07.10.2024), I receive a CRC error with "hd826.mp4". Other cutscenes seem to work alright but this one can't be viewed (using VLC) - even trying to unpacking only this file, I receive this error.

**To Reproduce**
1. Download the assets folder from "How To Play" section in "Releases"
2. Unzip the whole folder or only "hd826.mp4"
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by vitor251093** [comment]
Doesn't seem to be happening when I download it.

![2024-10-07_22-52](https://github.com/user-attachments/assets/ef789c25-d33f-44d2-89b0-75d21db55878)

Can you show a screenshot of the CRC error, or copy the whole error message?

**Comment by hyouriku** [comment]
<img width="423" alt="CRC error" src="https://github.com/user-attachments/assets/35f9d1b8-28bb-44d1-80c8-f53d968c2cc1">

Sorry, I posted this in the original post but I probably deleted it with the template together.
In VLC it flimmers around between 0:00 total time and -:--

Maybe I'll try download the assets again, maybe the download was corrupted in any way?

**Comment by hyouriku** [comment]
Alright, I don't know why, but somehow the zip file was somehow corrupt. After downloading it again (I wasn't able to try that as it took too long for to do so) it seems to work as intended. Maybe my network connection had a stutter.

Re-downloading it fixed that, thank you for your time.
