### ISSUE TITLE
broken sora emphasis on mission 51

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHMelonMix#252]
**Describe the bug**
when the screen flashes to sora in the lotus forest the game doesnt switch emphasis to him

**To Reproduce**
1. reach the lotus forest and let the cutscene play

**Expected behavior**
emphasis should be put on sora for the duration he shows up for

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Melon Mix Version: 0.4.4
 - ROM Region: US

**Additional context**
he shows for like , one single frame

**Comment by vitor251093** [comment]
Original for reference: https://youtu.be/RAaYHUEGWcY?t=573

**Comment by vitor251093** [comment]
[day_172_mission_51_lotus_forest.zip](https://github.com/user-attachments/files/18049449/day_172_mission_51_lotus_forest.zip)

**Comment by vitor251093** [comment]
Fixed on the latest Actions build
