### ISSUE TITLE
incorrect double screen instance in mission 90

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHMelonMix#253]
**Describe the bug**
during the scene where roxas places the device , the screen emphasis switches to dual screen mode with blue bars at the top and bottom

**To Reproduce**
1. go to the lamp chamber and watch the cutscene

**Expected behavior**
the screen should display as one

**Screenshots**
![Screenshot (2318)](https://github.com/user-attachments/assets/cd50fd77-b734-4831-a036-b6baae3923ca)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Melon Mix Version: 0.4.4
 - ROM Region: US

**Additional context**
unless i missed one , this is the only remaining scene with incorrect emphasis

**Comment by vitor251093** [comment]
[mission_90_main_menu_false_positive.zip](https://github.com/user-attachments/files/18049418/mission_90_main_menu_false_positive.zip)

**Comment by vitor251093** [comment]
Fixed in the latest Actions build
