### ISSUE TITLE
HD Cutscenes occupying half of the screen

### ISSUE THREAD

**Issue by DrBolt97x** [vitor251093/KHMelonMix#254]
Which cutscenes are supposed to be HD? Because my opening is the original grainy one
Is this a bug?

**Comment by DrBolt97x** [comment]
Yeah, fixed it the file wasn't named properly. New issue tho. Now, everything a cutscene starts, it's in split screen, and I have to toggle between full screen and windowed screen to fix it. Any idea why?

**Comment by vitor251093** [comment]
What do you mean with split screen? Do you mean it's occupying half of your screen only? Can you take a screenshot of the problem?

**Comment by DrBolt97x** [comment]
Sorry this was so long ago I don't remember. The situation on the new build tho, when a hd scene plays in fullscreen mode, the screen stays black but the audio plays fine. I have to toggle to windowed mode to make the video start playing. When I then toggle back to full screen it continues to play fine.

Also, the HD cutscene for Day 255 at the beginning of the game, after the credits, plays twice in a row.
