### ISSUE TITLE
Toggle for dialog box sizes

### ISSUE THREAD

**Issue by DrBolt97x** [vitor251093/KHMelonMix#255]
*Is there away to toggle between the current large text and the new one you had on older builds? With a big screen your new one was so much better

**Comment by vitor251093** [comment]
You will need to be more specific. Are you talking about the dialog box? Which older build version are you referring to? Use some screenshots to illustrate what you mean

**Comment by DrBolt97x** [comment]
The dialogue boxes that appeared when they are talking

**Comment by vitor251093** [comment]
You still need to tell me about which older build are you talking about. The text box had at least three different appearances since the project inception, so a screenshot would be helpful

**Comment by DrBolt97x** [comment]
Sorry I forgot about this. I got the image off Google but I think these text boxes were better. Maybe with bolder and bigger text in the box would be better but I still preferred it to the original ones, which I think were in the latest build.
![hq720 (1)](https://github.com/user-attachments/assets/4b50805a-22bf-4c72-94ec-6bce64bd52cf)

**Comment by DrBolt97x** [comment]
Dw I just downloaded the latest one. Perfect
