### ISSUE TITLE
Re:Coded pre-rendered cutscenes not sizing correctly

### ISSUE THREAD

**Issue by Mindofone** [vitor251093/KHMelonMix#256]
The cutscenes I've played through have incorrect sizing, making the primary window small and left-justified. I know, at least the cutscene in Disney castle after the opening does it.

If I had to guess, it's probably because the simple and clean opening displays the credits on the bottom screen, so they need to be displayed together. The script might be forgetting to resize the primary window after that is done.

First save state included is the issue happening, second save state should be during the opening. Just skip the cutscene and the second cutscene should be messed up.

Edit: This is on the steamdeck version

[Save States.zip](https://github.com/user-attachments/files/17483945/Save.States.zip)

**Comment by vitor251093** [comment]
Fixed the issue. It won't adapt a cutscene during runtime, but the opening and the credits will run in two screens, and the other cutscenes will run only with the top screen

Currently, the fix in only on the latest Actions build
