### ISSUE TITLE
Re:coded world map screen selection box is bugged

### ISSUE THREAD

**Issue by Mindofone** [vitor251093/KHMelonMix#262]
When going to the world map screen in re:coded, when you select either questploration or exit questploration, the confirmation text box will bug out. Half of it will be cut off, and the other half will be right-justified instead of center screen. I found this on the steamdeck.

![IMG_1549](https://github.com/user-attachments/assets/6889a2e8-1bc6-4408-87e9-b37c24b43e96)

**Comment by vitor251093** [comment]
Fixed in the latest Actions build
