### ISSUE TITLE
Re:coded stat matrix tab switching visual glitch

### ISSUE THREAD

**Issue by Mindofone** [vitor251093/KHMelonMix#265]
![IMG_1564](https://github.com/user-attachments/assets/f112db44-3e60-471b-8b51-b96236158931)

When entering the stat matrix and pressing the L or R button, there will be a visual glitch like the one depicted in the photo. It also seems to take slightly longer to switch screens as well. Steamdeck version.

**Comment by vitor251093** [comment]
Fixed on the latest Actions build
