### ISSUE TITLE
Level Up and Item Pickup Notifications do not show

### ISSUE THREAD

**Issue by RedDragoon101** [vitor251093/KHMelonMix#269]
**Describe the bug**
When the player Levels Up, Picks up an Item, levels a Keyblade or Command, or anything else that is supposed to pop up as a notification, just doesnt show up. you hear the sound, but no notification.

**To Reproduce**
1. Level Up
2. Dont see the notification
3. Profit?

**Expected behavior**
The Notification should appear in the corner

**Desktop (please complete the following information):**
 - Game: ReCoded
 - OS: Windows 10
 - Melon Mix Version: Latest Dev Build
 - ROM Region: US

**Comment by RedDragoon101** [comment]
![image_2024-11-06_061247974](https://github.com/user-attachments/assets/57ba7a6f-a134-44fc-a1fb-fb3aaffa974d)
This is what the notifs should look like on screen

**Comment by vitor251093** [comment]
Added support to all kinds of notifications on the latest Actions build
