### ISSUE TITLE
Enemy reports not showing properly? - Recoded

### ISSUE THREAD

**Issue by Draxirch** [vitor251093/KHMelonMix#271]
**Describe the bug**
The enemy profile page doesn't show correctly.

**To Reproduce**
1. Pause game
2. Go to the Data Report / Journal
3. Go to Enemy Reports
4. See problem

**Expected behavior**
Its supposed to be showing on two screens probably?

**Screenshots**
![20241119_121330](https://github.com/user-attachments/assets/411543eb-9b75-4bed-95bf-5322a068637f)

**Desktop (please complete the following information):**
 - Game: ReCoded
 - OS: Windows 11
 - Melon Mix Version: v0.5.0
 - ROM Region: US

**Comment by vitor251093** [comment]
Fixed on the latest Actions build
