### ISSUE TITLE
Captain Hook character portrait is glitched

### ISSUE THREAD

**Issue by KayFiOS** [vitor251093/KHMelonMix#272]
**Describe the bug**
A part of Captain Hook's character portrait will be duplicated and stretched, specifically the feather on his hat.

**To Reproduce**
![Img_2024_11_19_08_25_20](https://github.com/user-attachments/assets/3133e44b-50ed-49dd-8b96-77d293552162)
![Img_2024_11_19_08_25_20](https://github.com/user-attachments/assets/5c21a6b0-c840-4b74-a0e9-047841a215de)

1. Go to 'Mission 78' in Mission Mode
2. Defeat RotS
3. Watch the cutscene.

**Expected behavior**
Character portrait appears as normal 

**Screenshots**

**Desktop**
 - Game: Days
 - OS: Steam Deck OS
 - Melon Mix Version: 4.5
 - ROM Region: US

**Comment by vitor251093** [comment]
[days.zip](https://github.com/user-attachments/files/17853502/days.zip)

**Comment by vitor251093** [comment]
Fixed on the latest Actions build
