### ISSUE TITLE
Make Auto Screen Adjustment a toggleable option

### ISSUE THREAD

**Issue by Siveen** [vitor251093/KHMelonMix#275]
**Is your feature request related to a problem? Please describe.**
I have developed my own solution to deal with the issue of double screens, and while the auto screen adjust that KHMM implemented is a great feature, I would prefer using my own solution.

**Describe the solution you'd like**
An option toggle in MelonDS' settings that disables auto screening.

**Describe alternatives you've considered**
Making the toggle instead available by editing the batch file as a launch argument.

**Additional context**
Personally I really like the integrated Hybrid screen mode that MelonDS ships with, so I have based my OBS Filters on that.

**Comment by vitor251093** [comment]
Just added an option to the toml file. If you open the latest Actions build, and then edit your toml file, you will find something like that inside of it:

```
[KHDays_US]
DisableEnhancedGraphics = false
Language = ""
```

If your change the value of DisableEnhancedGraphics from false to true, the graphical enhancements will be disabled, and everything else will be kept.
