### ISSUE TITLE
Black screen after Intro

### ISSUE THREAD

**Issue by DragonKing2356** [vitor251093/KHMelonMix#279]
**Describe the bug**
When AFK on the title screen it will play the intro like normal. After the title disappears at the end its stuck on a black screen instead of returning to title.

**To Reproduce**
Stay afk on the title screen and let the intro play out. after the screen will go black.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Game: Days
 - OS: Windows 10
 - Melon Mix Version: 0.5.0 action build 752
 - ROM Region: US

**Comment by vitor251093** [comment]
Fixed on the latest Actions build
