### ISSUE TITLE
Steam deck control issues

### ISSUE THREAD

**Issue by Willdathrill26** [vitor251093/KHMelonMix#283]
For whatever reason,  the input config menu just crashes the appimage whenever I click on it. Because of this I can’t get the controls mapped and can’t play. I don’t know what’s causing this. From what I can tell, clicking the input config option causes a bunch of issues to pop up in the command prompt that opens whenever it’s run. None of the other menu options cause this to happen.

**Comment by vitor251093** [comment]
Which Melon Mix version are you using?

**Comment by Willdathrill26** [comment]
I’m using the appimage like the readme says. I’ve gotten the controls to work at this point after reinstalling the appimage, but now the background music isn’t working. The menu sounds and stuff are, just not the bgm.

**Comment by vitor251093** [comment]
That means you are using the 0.5.1 release. Use the 0.5.2 release and that will fix the no BGM problem
