### ISSUE TITLE
In-Game Default BGM no longer works

### ISSUE THREAD

**Issue by oblivioncth** [vitor251093/KHMelonMix#284]
**Describe the bug**
Any in-game music, aside from pre-rendered cutscenes no longer plays.

**To Reproduce**
1. Start MelonDS
2. Start a new game or load an existing save
3. Get to any point in the game where there should be music
4. Hear no music

**Expected behavior**
BGMs work :)

**Desktop (please complete the following information):**
 - Game: Days
 - OS: Windows 10
 - Melon Mix Version: 0.5.1
 - ROM Region: US

**Additional context**
Bisect shows 9500c71351eb7621a71c0d85f2a6ed35aaf571b0 to be the culprit.

Idk if it only affects specific configs/systems but I imagine there was just some oversight in the in-progress replacement of the MIDI tracks with their digital equivalents.

**Comment by vitor251093** [comment]
BGM replacement disabled on the master branch until we can get it working properly
