### ISSUE TITLE
No in game music for Days

### ISSUE THREAD

**Issue by Bobbypin12** [vitor251093/KHMelonMix#285]
**WARNING:** Fill this template, don't delete it. Otherwise, it will take longer for us to reproduce your bug, and it will take longer to be fixed. Delete this line after reading it.

**Describe the bug**
No background music for days in game. Affects story and mission mode.
Title screen and FMVs don't have the issue.

Ensured I had a clean download of 0.5.1 for windows.
Tried running 0.5.1 from that fresh download and had the issue.

Replacing MelonMix.exe 0.4.5 for 0.5.1 from my previous install also creates the issue.
Reverting that previous install back to MelonMix.exe 0.4.5 corrects the issue.

**To Reproduce**
1. Boot game using MelonMix.exe 0.5.1
2.  Start new story, load story save, or start mission mode
3.  No music once in game

**Expected behavior**
Background music expected to play in game

**Screenshots**
N/A

**Save state**
no save state. Happens with new game (either mode) and loading a save

**Desktop (please complete the following information):**
 - **Days**
 - **Happens everywhere in game (or at least where I tested):** 
 - **11** 
 - **0.5.1:** 
 - **US** 

**Additional context**
Recoded does not have this issue

**Comment by vitor251093** [comment]
That has been fixed on the latest Actions build, but wasn't included on a new release yet. I will be included in 0.5.2

**Comment by Bobbypin12** [comment]
Sounds good. Thank you
