### ISSUE TITLE
Validate if the ending credits and the "End" screen are working properly

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHMelonMix#79]
Credits and End screens will probably require scenes only for them. I haven't validate them yet.

https://www.youtube.com/watch?v=sc2lnd0mhNA

**Comment by sandwichwater** [comment]
unfortunately not , the credits have severe flashing and everything else displays side to side

**Comment by sandwichwater** [comment]
works well for the time being👍

**Comment by vitor251093** [comment]
In order to avoid the return of bug #70, I will need to revert this fix for now

**Comment by vitor251093** [comment]
Credits fixed by cutscene replacement.

End screen will be dealt with in #211
