### ISSUE TITLE
Lock-On toggle with 1 tap only

### ISSUE THREAD

**Issue by khHER0** [vitor251093/KHMelonMix#90]
Wondering if it's possible for a new MelonMix "input and hotkeys" option to assign a separate *single* hotkey/joypadButton to activate/deactivate enemy targeting "Lock-On" Mode for battles perhaps? Because the only way 358Days was designed to Lock-On toggle is by tapping the DS controlPad's "R Button" twice...

So I thought what if it's possible for a separate single hotkey/controllerButton tap's assignment to register as specifically executing a "double tap of the DS's/game's R Button" since personally "double-tapping" for me at least feels quite unfamiliar still relative to classic KH1/2/3 etc. for Lock-On?) 

For example all HD console versions of KH 1.5, 2.5, 2.8, 3 allow Lock-On Mode toggle with a single button tap, while the only KH games where Lock-On Mode toggle was executed by multiple buttons/taps were the original handheld platform game release versions on DS/3DS/PSP/etc. like 358Days 😅

//If it were possible, I'd personally try mapping "Lock-On" toggle to single-pressing the "R3" Button in a USB analog stick gamePad or R2 Trigger Button or something like that maybe? (in my own KH playing at least? Hehe :)

Anyway I've included a mockup image example to illustrate my add-on idea concept if it helps in case anyone else also favors adding this as a possible control feature? 🤩

![Melon Mix enhancement idea - Lock-On toggle by a separate button tap once each time only (to register the same as doubletapping the DS controlpad R button)](https://github.com/vitor251093/KHDays_FM/assets/168979478/90d32c21-78a4-4963-ae8e-7d19b91ea030)

**Comment by vitor251093** [comment]
Expanding on this idea, two new buttons will be added:
- Lock On (double R)
- Switch Target (R, but with a forced delay between taps, to avoid Lock On)

**Comment by vitor251093** [comment]
Implemented on the latest Actions builds
